module.exports = {
    ACTION: "ACTION",
    PATH: "PATH",
    SERVICE_NAME: "SERVICE_NAME",
    SERVICE_COMMANDS: "SERVICE_COMMANDS",
    EDITED_DATA: "EDITED_DATA",
    ADD_SERVICE_METHOD: "ADD_SERVICE_METHOD",
    CONFIRMATION: "CONFIRMATION",
    CONFIG_NAME: "CONFIG_NAME",
    SERVICE_LIST: "SERVICE_LIST",
    COMMAND_TO_RUN: "COMMAND_TO_RUN",
    SAVE_TYPE: "SAVE_TYPE",
}